# Generated by Django 4.0 on 2022-01-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=400, verbose_name='Description')),
                ('amount', models.IntegerField(max_length=100, verbose_name='amount')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
        ),
    ]
